### ISSUE TITLE
请问使用方法 流程是什么样的

### ISSUE THREAD

**Issue by 15949893621** [DanielHusx/DHXcodeAutoPackage#1]

**Comment by DanielHusx** [comment]
核心功能流程是
1. 点击右上方+号按钮进行添加任务，填写路径（支持文档路径自识别，以及.archiver, .ipa, .xcodeproj, .xcworkspace文件的解析）
2. 根据路径解析后的结果，进行再自定义项目配置（描述文件，BundleId，项目信息等）
3. 添加任务后，在主界面勾选一个或多个任务，再点击左上方的运行按钮，即可自动依次执行勾选的任务（编译导包）

其他功能，主要是围绕核心功能的完善配置，可自行探索
里面还有些bug，请见谅，后续会慢慢完善

**Comment by 15949893621** [comment]
您好!
    收到了您的回复,非常感谢!

> 2021年4月6日 上午11:03，Daniel ***@***.***> 写道：
> 
> 填写路径
